const mysql = require('mysql2/promise');
require('dotenv').config();

const dbConfig = {
  host: process.env.DB_HOST || 'localhost',
  port: process.env.DB_PORT || 3306,
  user: process.env.DB_USER || 'root',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_NAME || 'voting_system',
};

async function seedExtendedIndianNames() {
  const connection = await mysql.createConnection(dbConfig);
  
  try {
    console.log('🌱 Seeding extended Indian names database...');
    
    // Comprehensive list of Indian names (first names, last names, father/mother names)
    const extendedNames = [
      // Common First Names (Male)
      { token: 'rajesh', type: 'first_name', score: 0.95 },
      { token: 'kumar', type: 'first_name', score: 0.98 },
      { token: 'amit', type: 'first_name', score: 0.94 },
      { token: 'rahul', type: 'first_name', score: 0.95 },
      { token: 'suresh', type: 'first_name', score: 0.93 },
      { token: 'mahesh', type: 'first_name', score: 0.92 },
      { token: 'ramesh', type: 'first_name', score: 0.93 },
      { token: 'vijay', type: 'first_name', score: 0.94 },
      { token: 'ajay', type: 'first_name', score: 0.93 },
      { token: 'sanjay', type: 'first_name', score: 0.92 },
      { token: 'anil', type: 'first_name', score: 0.91 },
      { token: 'sunil', type: 'first_name', score: 0.91 },
      { token: 'manoj', type: 'first_name', score: 0.90 },
      { token: 'pradeep', type: 'first_name', score: 0.89 },
      { token: 'deepak', type: 'first_name', score: 0.90 },
      { token: 'sandeep', type: 'first_name', score: 0.89 },
      { token: 'naveen', type: 'first_name', score: 0.88 },
      { token: 'arun', type: 'first_name', score: 0.92 },
      { token: 'varun', type: 'first_name', score: 0.87 },
      { token: 'kiran', type: 'first_name', score: 0.88 },
      { token: 'rohit', type: 'first_name', score: 0.89 },
      { token: 'mohit', type: 'first_name', score: 0.88 },
      { token: 'nitin', type: 'first_name', score: 0.87 },
      { token: 'rakesh', type: 'first_name', score: 0.90 },
      { token: 'mukesh', type: 'first_name', score: 0.89 },
      { token: 'dinesh', type: 'first_name', score: 0.88 },
      { token: 'harish', type: 'first_name', score: 0.87 },
      { token: 'girish', type: 'first_name', score: 0.86 },
      { token: 'umesh', type: 'first_name', score: 0.87 },
      { token: 'suresh', type: 'first_name', score: 0.93 },
      { token: 'ram', type: 'first_name', score: 0.96 },
      { token: 'krishna', type: 'first_name', score: 0.95 },
      { token: 'shiva', type: 'first_name', score: 0.94 },
      { token: 'vishnu', type: 'first_name', score: 0.93 },
      { token: 'ganesh', type: 'first_name', score: 0.94 },
      { token: 'hanuman', type: 'first_name', score: 0.92 },
      { token: 'lakshman', type: 'first_name', score: 0.91 },
      { token: 'bharat', type: 'first_name', score: 0.90 },
      { token: 'arjun', type: 'first_name', score: 0.93 },
      { token: 'yudhishthir', type: 'first_name', score: 0.88 },
      { token: 'bhima', type: 'first_name', score: 0.87 },
      { token: 'nakul', type: 'first_name', score: 0.86 },
      { token: 'sahadev', type: 'first_name', score: 0.85 },
      { token: 'abhishek', type: 'first_name', score: 0.89 },
      { token: 'aditya', type: 'first_name', score: 0.88 },
      { token: 'akash', type: 'first_name', score: 0.87 },
      { token: 'aman', type: 'first_name', score: 0.88 },
      { token: 'anand', type: 'first_name', score: 0.89 },
      { token: 'ashish', type: 'first_name', score: 0.88 },
      { token: 'ashok', type: 'first_name', score: 0.90 },
      { token: 'bharat', type: 'first_name', score: 0.90 },
      { token: 'chetan', type: 'first_name', score: 0.87 },
      { token: 'dhanush', type: 'first_name', score: 0.86 },
      { token: 'gaurav', type: 'first_name', score: 0.88 },
      { token: 'harsh', type: 'first_name', score: 0.87 },
      { token: 'hemant', type: 'first_name', score: 0.86 },
      { token: 'ishaan', type: 'first_name', score: 0.87 },
      { token: 'jay', type: 'first_name', score: 0.89 },
      { token: 'karan', type: 'first_name', score: 0.88 },
      { token: 'kartik', type: 'first_name', score: 0.87 },
      { token: 'lokesh', type: 'first_name', score: 0.86 },
      { token: 'manish', type: 'first_name', score: 0.88 },
      { token: 'mayank', type: 'first_name', score: 0.87 },
      { token: 'neeraj', type: 'first_name', score: 0.88 },
      { token: 'omkar', type: 'first_name', score: 0.86 },
      { token: 'pankaj', type: 'first_name', score: 0.87 },
      { token: 'parth', type: 'first_name', score: 0.86 },
      { token: 'prakash', type: 'first_name', score: 0.89 },
      { token: 'pranav', type: 'first_name', score: 0.87 },
      { token: 'prashant', type: 'first_name', score: 0.88 },
      { token: 'raghav', type: 'first_name', score: 0.87 },
      { token: 'rajat', type: 'first_name', score: 0.88 },
      { token: 'rajeev', type: 'first_name', score: 0.89 },
      { token: 'ravi', type: 'first_name', score: 0.91 },
      { token: 'ritesh', type: 'first_name', score: 0.87 },
      { token: 'rohan', type: 'first_name', score: 0.88 },
      { token: 'sachin', type: 'first_name', score: 0.90 },
      { token: 'sameer', type: 'first_name', score: 0.88 },
      { token: 'siddharth', type: 'first_name', score: 0.89 },
      { token: 'sumit', type: 'first_name', score: 0.88 },
      { token: 'tushar', type: 'first_name', score: 0.87 },
      { token: 'uday', type: 'first_name', score: 0.86 },
      { token: 'utkarsh', type: 'first_name', score: 0.87 },
      { token: 'vaibhav', type: 'first_name', score: 0.88 },
      { token: 'vikas', type: 'first_name', score: 0.89 },
      { token: 'vikram', type: 'first_name', score: 0.88 },
      { token: 'vinay', type: 'first_name', score: 0.87 },
      { token: 'vivek', type: 'first_name', score: 0.88 },
      { token: 'yash', type: 'first_name', score: 0.87 },
      
      // Common First Names (Female)
      { token: 'priya', type: 'first_name', score: 0.95 },
      { token: 'kavita', type: 'first_name', score: 0.93 },
      { token: 'sunita', type: 'first_name', score: 0.92 },
      { token: 'anita', type: 'first_name', score: 0.91 },
      { token: 'neha', type: 'first_name', score: 0.94 },
      { token: 'pooja', type: 'first_name', score: 0.93 },
      { token: 'divya', type: 'first_name', score: 0.92 },
      { token: 'kavya', type: 'first_name', score: 0.91 },
      { token: 'riya', type: 'first_name', score: 0.90 },
      { token: 'sneha', type: 'first_name', score: 0.91 },
      { token: 'meera', type: 'first_name', score: 0.90 },
      { token: 'radha', type: 'first_name', score: 0.92 },
      { token: 'sita', type: 'first_name', score: 0.93 },
      { token: 'lakshmi', type: 'first_name', score: 0.94 },
      { token: 'saraswati', type: 'first_name', score: 0.91 },
      { token: 'durga', type: 'first_name', score: 0.90 },
      { token: 'parvati', type: 'first_name', score: 0.91 },
      { token: 'ganga', type: 'first_name', score: 0.89 },
      { token: 'yamuna', type: 'first_name', score: 0.88 },
      { token: 'anjali', type: 'first_name', score: 0.90 },
      { token: 'archana', type: 'first_name', score: 0.89 },
      { token: 'ashwini', type: 'first_name', score: 0.88 },
      { token: 'bhavana', type: 'first_name', score: 0.87 },
      { token: 'chitra', type: 'first_name', score: 0.88 },
      { token: 'deepika', type: 'first_name', score: 0.89 },
      { token: 'geeta', type: 'first_name', score: 0.90 },
      { token: 'harshita', type: 'first_name', score: 0.87 },
      { token: 'ishita', type: 'first_name', score: 0.88 },
      { token: 'jyoti', type: 'first_name', score: 0.89 },
      { token: 'kalyani', type: 'first_name', score: 0.87 },
      { token: 'kanchan', type: 'first_name', score: 0.86 },
      { token: 'kirti', type: 'first_name', score: 0.87 },
      { token: 'madhu', type: 'first_name', score: 0.88 },
      { token: 'manisha', type: 'first_name', score: 0.89 },
      { token: 'maya', type: 'first_name', score: 0.88 },
      { token: 'megha', type: 'first_name', score: 0.87 },
      { token: 'monika', type: 'first_name', score: 0.88 },
      { token: 'nandini', type: 'first_name', score: 0.87 },
      { token: 'nisha', type: 'first_name', score: 0.88 },
      { token: 'pallavi', type: 'first_name', score: 0.87 },
      { token: 'pavani', type: 'first_name', score: 0.86 },
      { token: 'priti', type: 'first_name', score: 0.87 },
      { token: 'rashmi', type: 'first_name', score: 0.88 },
      { token: 'rekha', type: 'first_name', score: 0.89 },
      { token: 'renuka', type: 'first_name', score: 0.87 },
      { token: 'ritu', type: 'first_name', score: 0.88 },
      { token: 'sadhana', type: 'first_name', score: 0.87 },
      { token: 'sandhya', type: 'first_name', score: 0.88 },
      { token: 'sarika', type: 'first_name', score: 0.87 },
      { token: 'shilpa', type: 'first_name', score: 0.88 },
      { token: 'shweta', type: 'first_name', score: 0.89 },
      { token: 'sonal', type: 'first_name', score: 0.88 },
      { token: 'sonia', type: 'first_name', score: 0.87 },
      { token: 'swati', type: 'first_name', score: 0.88 },
      { token: 'tanvi', type: 'first_name', score: 0.87 },
      { token: 'trisha', type: 'first_name', score: 0.86 },
      { token: 'urvashi', type: 'first_name', score: 0.87 },
      { token: 'vaishali', type: 'first_name', score: 0.88 },
      { token: 'varsha', type: 'first_name', score: 0.87 },
      { token: 'vidya', type: 'first_name', score: 0.88 },
      { token: 'vinita', type: 'first_name', score: 0.87 },
      
      // Last Names (already have many, adding more regional variations)
      { token: 'kumar', type: 'last_name', score: 0.98 },
      { token: 'singh', type: 'last_name', score: 0.98 },
      { token: 'patel', type: 'last_name', score: 0.97 },
      { token: 'sharma', type: 'last_name', score: 0.97 },
      { token: 'reddy', type: 'last_name', score: 0.96 },
      { token: 'rao', type: 'last_name', score: 0.95 },
      { token: 'naidu', type: 'last_name', score: 0.94 },
      { token: 'iyer', type: 'last_name', score: 0.93 },
      { token: 'iyengar', type: 'last_name', score: 0.92 },
      { token: 'menon', type: 'last_name', score: 0.91 },
      { token: 'nair', type: 'last_name', score: 0.95 },
      { token: 'pillai', type: 'last_name', score: 0.90 },
      { token: 'devi', type: 'last_name', score: 0.94 },
      { token: 'bai', type: 'last_name', score: 0.92 },
      { token: 'lal', type: 'last_name', score: 0.93 },
      { token: 'das', type: 'last_name', score: 0.91 },
      { token: 'dutta', type: 'last_name', score: 0.90 },
      { token: 'bose', type: 'last_name', score: 0.89 },
      { token: 'banerjee', type: 'last_name', score: 0.88 },
      { token: 'chatterjee', type: 'last_name', score: 0.87 },
      { token: 'mukherjee', type: 'last_name', score: 0.86 },
      { token: 'gupta', type: 'last_name', score: 0.96 },
      { token: 'jain', type: 'last_name', score: 0.94 },
      { token: 'agarwal', type: 'last_name', score: 0.93 },
      { token: 'goel', type: 'last_name', score: 0.91 },
      { token: 'mittal', type: 'last_name', score: 0.90 },
      { token: 'bansal', type: 'last_name', score: 0.89 },
      { token: 'garg', type: 'last_name', score: 0.88 },
      { token: 'malhotra', type: 'last_name', score: 0.87 },
      { token: 'kapoor', type: 'last_name', score: 0.86 },
      { token: 'khanna', type: 'last_name', score: 0.85 },
      { token: 'mehta', type: 'last_name', score: 0.92 },
      { token: 'shah', type: 'last_name', score: 0.94 },
      { token: 'desai', type: 'last_name', score: 0.91 },
      { token: 'joshi', type: 'last_name', score: 0.90 },
      { token: 'pandey', type: 'last_name', score: 0.89 },
      { token: 'tiwari', type: 'last_name', score: 0.88 },
      { token: 'mishra', type: 'last_name', score: 0.87 },
      { token: 'verma', type: 'last_name', score: 0.86 },
      { token: 'yadav', type: 'last_name', score: 0.95 },
      { token: 'khan', type: 'last_name', score: 0.97 },
      { token: 'ahmed', type: 'last_name', score: 0.95 },
      { token: 'hussain', type: 'last_name', score: 0.94 },
      { token: 'ali', type: 'last_name', score: 0.96 },
      { token: 'rahman', type: 'last_name', score: 0.93 },
      { token: 'sheikh', type: 'last_name', score: 0.92 },
      { token: 'choudhary', type: 'last_name', score: 0.91 },
      { token: 'thakur', type: 'last_name', score: 0.92 },
      { token: 'rajput', type: 'last_name', score: 0.90 },
      { token: 'rathore', type: 'last_name', score: 0.89 },
      { token: 'solanki', type: 'last_name', score: 0.88 },
      { token: 'parmar', type: 'last_name', score: 0.87 },
      { token: 'chauhan', type: 'last_name', score: 0.89 },
      { token: 'tomar', type: 'last_name', score: 0.88 },
      { token: 'saini', type: 'last_name', score: 0.87 },
      { token: 'maurya', type: 'last_name', score: 0.86 },
      { token: 'gautam', type: 'last_name', score: 0.88 },
      { token: 'saxena', type: 'last_name', score: 0.87 },
      { token: 'trivedi', type: 'last_name', score: 0.86 },
      { token: 'shukla', type: 'last_name', score: 0.88 },
      { token: 'dwivedi', type: 'last_name', score: 0.87 },
      { token: 'tripathi', type: 'last_name', score: 0.88 },
      { token: 'pathak', type: 'last_name', score: 0.87 },
      { token: 'upadhyay', type: 'last_name', score: 0.86 },
      { token: 'acharya', type: 'last_name', score: 0.87 },
      { token: 'bhatt', type: 'last_name', score: 0.88 },
      { token: 'brahmbhatt', type: 'last_name', score: 0.85 },
      { token: 'shah', type: 'last_name', score: 0.94 },
      { token: 'modi', type: 'last_name', score: 0.90 },
      { token: 'patel', type: 'last_name', score: 0.97 },
      { token: 'desai', type: 'last_name', score: 0.91 },
      { token: 'shah', type: 'last_name', score: 0.94 },
      { token: 'mehta', type: 'last_name', score: 0.92 },
      { token: 'gandhi', type: 'last_name', score: 0.93 },
      { token: 'ambani', type: 'last_name', score: 0.85 },
      { token: 'tata', type: 'last_name', score: 0.86 },
      { token: 'birla', type: 'last_name', score: 0.85 },
      { token: 'wadia', type: 'last_name', score: 0.84 },
      { token: 'godrej', type: 'last_name', score: 0.83 },
      { token: 'mahindra', type: 'last_name', score: 0.84 },
      { token: 'bajaj', type: 'last_name', score: 0.85 },
      { token: 'hinduja', type: 'last_name', score: 0.83 },
      { token: 'adani', type: 'last_name', score: 0.84 },
      { token: 'premji', type: 'last_name', score: 0.83 },
      { token: 'murthy', type: 'last_name', score: 0.85 },
      { token: 'narayana', type: 'last_name', score: 0.84 },
      { token: 'reddy', type: 'last_name', score: 0.96 },
      { token: 'rao', type: 'last_name', score: 0.95 },
      { token: 'naidu', type: 'last_name', score: 0.94 },
      { token: 'chowdary', type: 'last_name', score: 0.92 },
      { token: 'goud', type: 'last_name', score: 0.91 },
      { token: 'velama', type: 'last_name', score: 0.90 },
      { token: 'kamma', type: 'last_name', score: 0.89 },
      { token: 'kapu', type: 'last_name', score: 0.88 },
      { token: 'balija', type: 'last_name', score: 0.87 },
      { token: 'komati', type: 'last_name', score: 0.86 },
      { token: 'vysya', type: 'last_name', score: 0.85 },
      { token: 'setty', type: 'last_name', score: 0.84 },
      { token: 'chetty', type: 'last_name', score: 0.83 },
      { token: 'iyer', type: 'last_name', score: 0.93 },
      { token: 'iyengar', type: 'last_name', score: 0.92 },
      { token: 'menon', type: 'last_name', score: 0.91 },
      { token: 'nair', type: 'last_name', score: 0.95 },
      { token: 'pillai', type: 'last_name', score: 0.90 },
      { token: 'nambiar', type: 'last_name', score: 0.89 },
      { token: 'unni', type: 'last_name', score: 0.88 },
      { token: 'warrier', type: 'last_name', score: 0.87 },
      { token: 'namboothiri', type: 'last_name', score: 0.86 },
      { token: 'embranthiri', type: 'last_name', score: 0.85 },
      { token: 'marar', type: 'last_name', score: 0.84 },
      { token: 'kurup', type: 'last_name', score: 0.83 },
      { token: 'panicker', type: 'last_name', score: 0.82 },
      { token: 'thampan', type: 'last_name', score: 0.81 },
      { token: 'namboothiripad', type: 'last_name', score: 0.80 },
      { token: 'acharya', type: 'last_name', score: 0.87 },
      { token: 'bhatt', type: 'last_name', score: 0.88 },
      { token: 'brahmbhatt', type: 'last_name', score: 0.85 },
      { token: 'joshi', type: 'last_name', score: 0.90 },
      { token: 'dave', type: 'last_name', score: 0.86 },
      { token: 'trivedi', type: 'last_name', score: 0.86 },
      { token: 'shukla', type: 'last_name', score: 0.88 },
      { token: 'dwivedi', type: 'last_name', score: 0.87 },
      { token: 'tripathi', type: 'last_name', score: 0.88 },
      { token: 'pathak', type: 'last_name', score: 0.87 },
      { token: 'upadhyay', type: 'last_name', score: 0.86 },
      { token: 'pandit', type: 'last_name', score: 0.87 },
      { token: 'shastri', type: 'last_name', score: 0.86 },
      { token: 'vedi', type: 'last_name', score: 0.85 },
      { token: 'vaidya', type: 'last_name', score: 0.84 },
      { token: 'sharma', type: 'last_name', score: 0.97 },
      { token: 'verma', type: 'last_name', score: 0.86 },
      { token: 'yadav', type: 'last_name', score: 0.95 },
      { token: 'kushwaha', type: 'last_name', score: 0.88 },
      { token: 'koiri', type: 'last_name', score: 0.87 },
      { token: 'maurya', type: 'last_name', score: 0.86 },
      { token: 'gautam', type: 'last_name', score: 0.88 },
      { token: 'saini', type: 'last_name', score: 0.87 },
      { token: 'chauhan', type: 'last_name', score: 0.89 },
      { token: 'tomar', type: 'last_name', score: 0.88 },
      { token: 'rathore', type: 'last_name', score: 0.89 },
      { token: 'solanki', type: 'last_name', score: 0.88 },
      { token: 'parmar', type: 'last_name', score: 0.87 },
      { token: 'rajput', type: 'last_name', score: 0.90 },
      { token: 'thakur', type: 'last_name', score: 0.92 },
      { token: 'choudhary', type: 'last_name', score: 0.91 },
      { token: 'rana', type: 'last_name', score: 0.89 },
      { token: 'rawat', type: 'last_name', score: 0.88 },
      { token: 'bisht', type: 'last_name', score: 0.87 },
      { token: 'negi', type: 'last_name', score: 0.86 },
      { token: 'bhatt', type: 'last_name', score: 0.88 },
      { token: 'bhandari', type: 'last_name', score: 0.87 },
      { token: 'karki', type: 'last_name', score: 0.86 },
      { token: 'thapa', type: 'last_name', score: 0.85 },
      { token: 'magar', type: 'last_name', score: 0.84 },
      { token: 'rai', type: 'last_name', score: 0.88 },
      { token: 'limbu', type: 'last_name', score: 0.85 },
      { token: 'tamang', type: 'last_name', score: 0.84 },
      { token: 'gurung', type: 'last_name', score: 0.83 },
      { token: 'sherpa', type: 'last_name', score: 0.82 },
      { token: 'newar', type: 'last_name', score: 0.81 },
      { token: 'khan', type: 'last_name', score: 0.97 },
      { token: 'ahmed', type: 'last_name', score: 0.95 },
      { token: 'hussain', type: 'last_name', score: 0.94 },
      { token: 'ali', type: 'last_name', score: 0.96 },
      { token: 'rahman', type: 'last_name', score: 0.93 },
      { token: 'sheikh', type: 'last_name', score: 0.92 },
      { token: 'malik', type: 'last_name', score: 0.91 },
      { token: 'qureshi', type: 'last_name', score: 0.90 },
      { token: 'ansari', type: 'last_name', score: 0.89 },
      { token: 'hashmi', type: 'last_name', score: 0.88 },
      { token: 'syed', type: 'last_name', score: 0.87 },
      { token: 'mirza', type: 'last_name', score: 0.86 },
      { token: 'baig', type: 'last_name', score: 0.85 },
      { token: 'pathan', type: 'last_name', score: 0.84 },
      { token: 'mansoori', type: 'last_name', score: 0.83 },
      { token: 'momin', type: 'last_name', score: 0.82 },
      { token: 'mansuri', type: 'last_name', score: 0.81 },
      { token: 'chishti', type: 'last_name', score: 0.80 },
      { token: 'naqvi', type: 'last_name', score: 0.79 },
      { token: 'rizvi', type: 'last_name', score: 0.78 },
      { token: 'zaidi', type: 'last_name', score: 0.77 },
      { token: 'abidi', type: 'last_name', score: 0.76 },
      { token: 'jafri', type: 'last_name', score: 0.75 },
      { token: 'husaini', type: 'last_name', score: 0.74 },
      { token: 'karbalai', type: 'last_name', score: 0.73 },
      { token: 'mohammadi', type: 'last_name', score: 0.72 },
      { token: 'hassan', type: 'last_name', score: 0.91 },
      { token: 'hassanain', type: 'last_name', score: 0.90 },
      { token: 'hussaini', type: 'last_name', score: 0.89 },
      { token: 'hussainy', type: 'last_name', score: 0.88 },
      { token: 'ibrahim', type: 'last_name', score: 0.87 },
      { token: 'ismail', type: 'last_name', score: 0.86 },
      { token: 'ismaili', type: 'last_name', score: 0.85 },
      { token: 'jafari', type: 'last_name', score: 0.84 },
      { token: 'jawad', type: 'last_name', score: 0.83 },
      { token: 'kadri', type: 'last_name', score: 0.82 },
      { token: 'karbalai', type: 'last_name', score: 0.73 },
      { token: 'kazmi', type: 'last_name', score: 0.81 },
      { token: 'khwaja', type: 'last_name', score: 0.80 },
      { token: 'lakdawala', type: 'last_name', score: 0.79 },
      { token: 'machiswala', type: 'last_name', score: 0.78 },
      { token: 'madni', type: 'last_name', score: 0.77 },
      { token: 'mahdavi', type: 'last_name', score: 0.76 },
      { token: 'majeed', type: 'last_name', score: 0.75 },
      { token: 'makki', type: 'last_name', score: 0.74 },
      { token: 'malik', type: 'last_name', score: 0.91 },
      { token: 'mansoori', type: 'last_name', score: 0.83 },
      { token: 'mansuri', type: 'last_name', score: 0.81 },
      { token: 'memon', type: 'last_name', score: 0.90 },
      { token: 'merchant', type: 'last_name', score: 0.89 },
      { token: 'mian', type: 'last_name', score: 0.88 },
      { token: 'mian', type: 'last_name', score: 0.88 },
      { token: 'mir', type: 'last_name', score: 0.87 },
      { token: 'mirza', type: 'last_name', score: 0.86 },
      { token: 'mohammadi', type: 'last_name', score: 0.72 },
      { token: 'mohammed', type: 'last_name', score: 0.85 },
      { token: 'mohiuddin', type: 'last_name', score: 0.84 },
      { token: 'momin', type: 'last_name', score: 0.82 },
      { token: 'mukadam', type: 'last_name', score: 0.81 },
      { token: 'naqvi', type: 'last_name', score: 0.79 },
      { token: 'nawab', type: 'last_name', score: 0.78 },
      { token: 'nizami', type: 'last_name', score: 0.77 },
      { token: 'pathan', type: 'last_name', score: 0.84 },
      { token: 'peerzada', type: 'last_name', score: 0.76 },
      { token: 'pirzada', type: 'last_name', score: 0.75 },
      { token: 'qadri', type: 'last_name', score: 0.74 },
      { token: 'qureshi', type: 'last_name', score: 0.90 },
      { token: 'raza', type: 'last_name', score: 0.73 },
      { token: 'razvi', type: 'last_name', score: 0.72 },
      { token: 'rizvi', type: 'last_name', score: 0.78 },
      { token: 'sabri', type: 'last_name', score: 0.71 },
      { token: 'sadr', type: 'last_name', score: 0.70 },
      { token: 'saiyad', type: 'last_name', score: 0.69 },
      { token: 'sakina', type: 'last_name', score: 0.68 },
      { token: 'sayeed', type: 'last_name', score: 0.67 },
      { token: 'sayyid', type: 'last_name', score: 0.66 },
      { token: 'shah', type: 'last_name', score: 0.94 },
      { token: 'shaikh', type: 'last_name', score: 0.65 },
      { token: 'sheikh', type: 'last_name', score: 0.92 },
      { token: 'shia', type: 'last_name', score: 0.64 },
      { token: 'shirazi', type: 'last_name', score: 0.63 },
      { token: 'siddiqui', type: 'last_name', score: 0.92 },
      { token: 'syed', type: 'last_name', score: 0.87 },
      { token: 'taheri', type: 'last_name', score: 0.62 },
      { token: 'turabi', type: 'last_name', score: 0.61 },
      { token: 'usmani', type: 'last_name', score: 0.60 },
      { token: 'warsi', type: 'last_name', score: 0.59 },
      { token: 'zaidi', type: 'last_name', score: 0.77 },
      { token: 'zainab', type: 'last_name', score: 0.58 },
      { token: 'zaki', type: 'last_name', score: 0.57 },
      { token: 'zakir', type: 'last_name', score: 0.56 },
      { token: 'zaman', type: 'last_name', score: 0.55 },
      { token: 'zubair', type: 'last_name', score: 0.54 },
      
      // Father/Mother/Guardian names (use same as first_name)
      // These will be matched against first_name patterns
    ];
    
    console.log(`📝 Seeding ${extendedNames.length} extended Indian names...`);
    
    let inserted = 0;
    let updated = 0;
    let skipped = 0;
    
    for (const name of extendedNames) {
      try {
        const [result] = await connection.query(
          `INSERT INTO name_frequency_lookup (name_token, name_type, frequency_score)
           VALUES (?, ?, ?)
           ON DUPLICATE KEY UPDATE frequency_score = GREATEST(frequency_score, VALUES(frequency_score))`,
          [name.token.toLowerCase(), name.type, name.score]
        );
        
        if (result.affectedRows === 1) {
          inserted++;
        } else {
          updated++;
        }
      } catch (e) {
        skipped++;
        // Ignore errors
      }
    }
    
    console.log(`✅ Seeded ${extendedNames.length} names: ${inserted} inserted, ${updated} updated, ${skipped} skipped`);
    
  } catch (error) {
    console.error('❌ Error seeding extended names:', error);
    throw error;
  } finally {
    await connection.end();
  }
}

// Run if called directly
if (require.main === module) {
  seedExtendedIndianNames()
    .then(() => {
      console.log('✅ Extended name seeding completed');
      process.exit(0);
    })
    .catch((error) => {
      console.error('❌ Extended name seeding failed:', error);
      process.exit(1);
    });
}

module.exports = seedExtendedIndianNames;

